### ISSUE TITLE
Warning: Unexpected ref object provided for div. Use either a ref-setter function or React.createRef().

### ISSUE THREAD

**Issue by billyzduke** [bitworking/react-gsap#37] opened 2021-02-16 11:02 UTC
This library looks awesome, but so far I can't get it to function, at least not in the context I'm trying to use it in (Gatsby w/ styled-components)... Here's the relevant code that produces the above error (2nd line of the error says: "in div (created by styled__PolybagBack)"

`import { Timeline, Tween } from 'react-gsap'`
`import { BannerCanvas, BannerScaler, BannerWrapper, PolybagBack, PolybagFront, Slipcase } from './styled'`

`const Banner = (props) => {`
`  const bannerMeat = (`
`    <BannerCanvas>`
`      <BannerScaler ref={bcb} style={scaleStyle}>`
`        <Timeline target={`
`          <PolybagBack>`
`            <Slipcase />`
`            <PolybagFront />`
`          </PolybagBack>`
`        }>`
`          <Tween to={{ x: "398px", rotation: 360 }} duration={2} ease="back.out(1.7)" />`
`        </Timeline>`
`      </BannerScaler>`
`    </BannerCanvas>`
`  )`
` `
`  return (`
`    <div id={props.banner}>`
`        <BannerWrapper>`
`          {bannerMeat}`
`        </BannerWrapper>`
`    </div>`
`  )`
`}`

Not sure what to try next... PolybagBack doesn't have or need an explicit ref, although I take the error to mean that styled-components is giving it one. There is a useEffect hook I left out above that scales BannerScaler to the window width.

**Comment by billyzduke** [comment] 2021-02-16 11:15
FYI, it does work when I removed the styled-components and use an inline-styled div.

**Comment by billyzduke** [comment] 2021-02-17 11:45
Just to give you an update, I think I've reached the point where continuing to struggle with this library is going to take longer than simply working without it. Having to use non-styled-component JSX elements for containers means that I have to create a separate layer of styles for those elements (if I want classes for them or any chance to abstract away huge inline style blocks). I'm also getting fatal errors when I nest one TimeLine inside another, which makes matching up complex animations with sub-components extremely time-consuming. I gave it fair shake, but I think I'm going back to the drawing board.

**Comment by TM818** [comment] 2021-02-23 02:31
> Just to give you an update, I think I've reached the point where continuing to struggle with this library is going to take longer than simply working without it. Having to use non-styled-component JSX elements for containers means that I have to create a separate layer of styles for those elements (if I want classes for them or any chance to abstract away huge inline style blocks). I'm also getting fatal errors when I nest one TimeLine inside another, which makes matching up complex animations with sub-components extremely time-consuming. I gave it a fair shake, but I think I'm going back to the drawing board.

Well, looks like no one is responding to your questions, so this seems to be a reasonable direction.

**Comment by bitworking** [comment] 2021-03-31 21:09
This is hard to tell. I would need a minimal reproduction code.

**Comment by bitworking** [comment] 2021-04-01 14:51
Could be fixed with version 2.3.0 because I optimized the way refs are handled. Refs will be merged now.

**Comment by bitworking** [comment] 2021-04-02 20:00
You are right. Normal forward ref components like a styled-component component could not be used as target. I'm working on that right now.

**Comment by bitworking** [comment] 2021-04-02 21:47
In version 3.1.0 styled-components as target are possible.

**Closed by bitworking** 2021-04-02 21:47 UTC
Labels: help wanted
